name        'magyarjeti-ylib'
version     '0.1.0'
author      'Magyar Jeti Zrt.'
source      'git://github.com/magyarjeti/puppet-ylib'
license     'MIT'
summary     'Yeti Standard Library'
description 'Useful extensions for module development'
